version: '3.8'
services:
  web:
    image: php:8.3-apache
    container_name: web
    ports:
      - "80:80"
      - "8123:8123"
    volumes:
      - ./html:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./sites-enabled/cv-web.conf:/etc/apache2/sites-enabled/cv-web.conf
      - ./sites-enabled/blog-web.conf:/etc/apache2/sites-enabled/blog-web.conf
      - ./sites-enabled/owncloud.conf:/etc/apache2/sites-enabled/owncloud.conf
    depends_on:
      - db
    command: apache2ctl -D FOREGROUND

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
