version: '3.8'
services:
  web:
    image: php:8.3-apache        # Imagen Apache con PHP 8.3 integrado
    container_name: apache_php   # Nombre opcional del contenedor
    ports:
      - "80:80"                  # Puertos HTTP estándar
      - "8123:8123"              # Puerto para www.stefsec.com:8123 (OwnCloud)
    volumes:
      - ./www:/var/www           # Monta la carpeta con archivos web y configuraciones en /var/www
      - ./apache2/sites:/etc/apache2/sites-available   # Archivos de sitios virtuales
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf:ro # Config global de Apache (solo lectura)
    command: /bin/bash -c "mkdir -p /etc/apache2/logs && a2ensite cv-web.conf blog-web.conf owncloud-web.conf && apache2-foreground"

  db:
    image: mariadb:latest        # Servidor MariaDB/MySQL
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root    # Contraseña root de MariaDB
      - MYSQL_DATABASE=prueba       # (Opcional) Crear BD de prueba
      - MYSQL_USER=prueba           # (Opcional) Crear usuario de prueba
      - MYSQL_PASSWORD=prueba       # (Opcional) Contraseña del usuario de prueba
    volumes:
      - db_data:/var/lib/mysql   # Volumen para persistir datos de la BD
    # **Nota:** No se expone puerto, solo accesible vía red interna Docker

  phpmyadmin:
    image: phpmyadmin:latest     # Interfaz phpMyAdmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db             # Conectar al servicio "db" (MariaDB)
      - MYSQL_ROOT_PASSWORD=MiPassword123  # Contraseña root de MariaDB (misma definida arriba)
    ports:
      - "8080:80"               # phpMyAdmin accesible en http://localhost:8080
    depends_on:
      - db

volumes:
  db_data:
